### ISSUE TITLE
Does not work on port 53

### ISSUE THREAD

**Issue by talesam** [isystem-io/wireguard-aws#3]
Does anyone know how I squeeze wireguard on AWS on port 53? Does not work, from the conflict of doors

**Comment by jadolg** [comment]
If you are using ubuntu it's very possible systemd-resolved is taking the port from you :-(
I have had the same problem as some of my VPNs ship with an internal DNS and I find myself doing this all the time https://gist.github.com/zoilomora/f7d264cefbb589f3f1b1fc2cea2c844c
Hope it works for you.

**Comment by talesam** [comment]
I managed to solve it in a very simple way ...

Edit the file: /etc/systemd/resolved.conf
and leave it like this: DNSStubListener=no

**Comment by jadolg** [comment]
I think you should close the issue then ;-)

**Comment by talesam** [comment]
;-)
